In [24]:
import pandas as pd
# FIFA TEAM STATS FOR WC 2018 upto R16
df = pd.read_csv('fifa_team_stats.csv')
# MATCHES RESULTS IN WC 2018 upto R16
matches = pd.read_csv('ALL_MATCHES.csv')
matches.head()

,Team_1,Team_2,attempts_off_target_1,attempts_off_target_2,attempts_on_target_1,attempts_on_target_2,clearances_1,clearances_2,goals_against_1,goals_against_2,goals_scored_1,goals_scored_2,matches_played_1,matches_played_2,results,shots_attempted_1,shots_attempted_2,shots_blocked_1,shots_blocked_2
0,Russia,Saudi Arabia,16,16,19,10,176,67,7,7,10,2,5,3,1,46,36,11,10
1,Egypt,Uruguay,17,26,5,22,95,109,6,3,2,6,3,5,0,29,61,7,13
2,Morocco,Iran,18,15,10,4,62,91,4,2,2,1,3,3,0,35,21,7,2
3,Portugal,Spain,20,28,14,21,87,36,6,6,6,6,4,4,0,52,70,18,21
4,France,Australia,27,14,19,8,135,83,4,5,8,2,5,3,1,56,32,10,10

In [25]:
#matches['results']

In [26]:
#res=[1,0,0,0.5,0.67,0.5,0,1,0,0,1,1,3,1,1,1,3,1,1,0,1,1,0,2,2,1,5,1,2,6,2,0,3,2,2,1,0,0,1,1,2,0,0,2,0,0,1,0,4,2,1,1,2,3,1,1,0,1,0,2,0,1,1,3,1,1,1,0,1,1,1,0,0,2,2,2,1,0,0,1,1,0,3,0,0,2,2,2,1,1,2,3,0,1,2,1,2,0,2,2,0,3,2,2,1,1,2,1,3,1,1,1,0,2,0,1,2,2,2,2]
#print (len(res))
res = [1,0,0,0.5,0.67,0.5,0,1,0,0,0.5,1,1,0.33,0.33,0.33,0.75,1,1,0,0.5,1,0,1,1,0.33,0.714,0.33,0.67,0.857,0.5,0,1,0.67,0.5,0.5,0,0.5,0.33,0.33,1,0,0,0.5,0,0,0.33,0,0.55,0.67,0.5,0.5,1,0.6,1,0.5,0,0.33,0,0.5]
# Normailizing
matches['results']=res

matches['goals_scored_1']=matches['goals_scored_1']/matches['matches_played_1']

matches['goals_scored_2']=matches['goals_scored_2']/matches['matches_played_2']

matches['goals_against_2']=matches['goals_against_2']/matches['matches_played_2']

matches['attempts_on_target_2']=matches['attempts_on_target_2']/matches['matches_played_2']

matches['shots_attempted_2']=matches['shots_attempted_2']/matches['matches_played_2']

matches['attempts_off_target_2']=matches['attempts_off_target_2']/matches['matches_played_2']

matches['shots_blocked_2']=matches['shots_blocked_2']/matches['matches_played_2']

matches['clearances_2']=matches['clearances_2']/matches['matches_played_2']

matches['goals_against_1']=matches['goals_against_1']/matches['matches_played_1']

matches['attempts_on_target_1']=matches['attempts_on_target_1']/matches['matches_played_1']

matches['shots_attempted_1']=matches['shots_attempted_1']/matches['matches_played_1']

matches['attempts_off_target_1']=matches['attempts_off_target_1']/matches['matches_played_1']

matches['shots_blocked_1']=matches['shots_blocked_1']/matches['matches_played_1']

matches['clearances_1']=matches['clearances_1']/matches['matches_played_1']

matches.head()
matches_2 = pd.DataFrame()
visited=[]
for col in matches.columns:
    c_name = str(col)
    if ('result' not in c_name):
        col_names = c_name.split('_')
        y = len(col_names)
        c_name_2 = ""
        for j in range(y-1):
            if (c_name_2):
                c_name_2 = c_name_2 + "_"
            c_name_2=c_name_2 + col_names[j]
        if (c_name_2 not in visited):
            matches_2[c_name_2+"_2"]=matches[col]
            visited.append(c_name_2)
        else:
            matches_2[c_name_2+"_1"]=matches[col]
    else:
        matches_2['results']=1-matches['results']
matches_2.head()
matches=matches.append(matches_2)
matches = matches.reset_index(drop=True)

matches[matches['Team_1']=='Russia']
matches[48:]

,Team_1,Team_2,attempts_off_target_1,attempts_off_target_2,attempts_on_target_1,attempts_on_target_2,clearances_1,clearances_2,goals_against_1,goals_against_2,goals_scored_1,goals_scored_2,matches_played_1,matches_played_2,results,shots_attempted_1,shots_attempted_2,shots_blocked_1,shots_blocked_2
48,France,Argentina,5.400000,4.000000,3.800000,4.500000,27.000000,18.000000,0.800000,2.250000,1.600000,1.500000,5,4,0.55,11.200000,13.250000,2.000000,4.750000
49,Uruguay,Portugal,5.200000,5.000000,4.400000,3.500000,21.800000,21.750000,0.600000,1.500000,1.200000,1.500000,5,4,0.67,12.200000,13.000000,2.600000,4.500000
50,Spain,Russia,7.000000,3.200000,5.250000,3.800000,9.000000,35.200000,1.500000,1.400000,1.500000,2.000000,4,5,0.50,17.500000,9.200000,5.250000,2.200000
51,Croatia,Denmark,7.800000,5.500000,3.800000,3.000000,28.800000,26.250000,0.800000,0.500000,1.800000,0.750000,5,4,0.50,15.600000,10.000000,4.000000,1.500000
52,Spain,Mexico,7.000000,6.000000,5.250000,3.250000,9.000000,23.750000,1.500000,1.500000,1.500000,0.750000,4,4,1.00,17.500000,14.250000,5.250000,5.000000
53,Belgium,Japan,6.400000,3.750000,6.600000,4.000000,21.000000,30.500000,1.000000,1.750000,2.600000,1.500000,5,4,0.60,17.000000,10.500000,4.000000,2.750000
54,Sweden,Switzerland,4.400000,5.500000,4.200000,3.500000,37.400000,16.000000,0.800000,1.250000,1.000000,1.250000,5,4,1.00,11.000000,14.000000,2.400000,5.000000
55,Columbia,England,3.500000,6.000000,3.000000,3.800000,25.750000,15.600000,0.750000,0.800000,1.500000,2.200000,4,5,0.50,9.750000,14.000000,3.250000,4.200000
56,Uruguay,France,5.200000,5.400000,4.400000,3.800000,21.800000,27.000000,0.600000,0.800000,1.200000,1.600000,5,5,0.00,12.200000,11.200000,2.600000,2.000000
57,Brazil,Belgium,7.000000,6.400000,7.600000,6.600000,18.200000,21.000000,0.600000,1.000000,1.600000,2.600000,5,5,0.33,20.600000,17.000000,6.000000,4.000000
58,Sweden,England,4.400000,6.000000,4.200000,3.800000,37.400000,15.600000,0.800000,0.800000,1.000000,2.200000,5,5,0.00,11.000000,14.000000,2.400000,4.200000
59,Russia,Croatia,3.200000,7.800000,3.800000,3.800000,35.200000,28.800000,1.400000,0.800000,2.000000,1.800000,5,5,0.50,9.200000,15.600000,2.200000,4.000000
60,Saudi Arabia,Russia,5.333333,3.200000,3.333333,3.800000,22.333333,35.200000,2.333333,1.400000,0.666667,2.000000,3,5,0.00,12.000000,9.200000,3.333333,2.200000
61,Uruguay,Egypt,5.200000,5.666667,4.400000,1.666667,21.800000,31.666667,0.600000,2.000000,1.200000,0.666667,5,3,1.00,12.200000,9.666667,2.600000,2.333333
62,Iran,Morocco,5.000000,6.000000,1.333333,3.333333,30.333333,20.666667,0.666667,1.333333,0.333333,0.666667,3,3,1.00,7.000000,11.666667,0.666667,2.333333
63,Spain,Portugal,7.000000,5.000000,5.250000,3.500000,9.000000,21.750000,1.500000,1.500000,1.500000,1.500000,4,4,0.50,17.500000,13.000000,5.250000,4.500000
64,Australia,France,4.666667,5.400000,2.666667,3.800000,27.666667,27.000000,1.666667,0.800000,0.666667,1.600000,3,5,0.33,10.666667,11.200000,3.333333,2.000000
65,Iceland,Argentina,6.333333,4.000000,4.000000,4.500000,26.666667,18.000000,1.666667,2.250000,0.666667,1.500000,3,4,0.50,12.000000,13.250000,1.666667,4.750000
66,Denmark,Peru,5.500000,4.666667,3.000000,3.666667,26.250000,20.000000,0.500000,0.666667,0.750000,0.666667,4,3,1.00,10.000000,10.666667,1.500000,2.333333
67,Nigeria,Croatia,5.333333,7.800000,3.000000,3.800000,32.000000,28.800000,1.333333,0.800000,1.000000,1.800000,3,5,0.00,13.000000,15.600000,4.666667,4.000000
68,Serbia,Costa Rica,5.666667,4.333333,2.333333,3.000000,25.333333,32.333333,1.333333,1.666667,0.666667,0.333333,3,3,1.00,10.666667,9.333333,2.666667,2.000000
69,Mexico,Germany,6.000000,8.000000,3.250000,6.666667,23.750000,11.666667,1.500000,1.333333,0.750000,0.666667,4,3,1.00,14.250000,22.333333,5.000000,7.666667
70,Switzerland,Brazil,5.500000,7.000000,3.500000,7.600000,16.000000,18.200000,1.250000,0.600000,1.250000,1.600000,4,5,0.50,14.000000,20.600000,5.000000,6.000000
71,Korea Republic,Sweden,3.000000,4.400000,3.666667,4.200000,31.333333,37.400000,1.000000,0.800000,1.000000,1.000000,3,5,0.00,11.000000,11.000000,4.333333,2.400000
72,Panama,Belgium,4.333333,6.400000,2.666667,6.600000,24.333333,21.000000,3.666667,1.000000,0.333333,2.600000,3,5,0.00,7.666667,17.000000,0.666667,4.000000
73,England,Tunisia,6.000000,4.333333,3.800000,4.333333,15.600000,19.333333,0.800000,2.666667,2.200000,1.666667,5,3,0.67,14.000000,12.000000,4.200000,3.333333
74,Japan,Columbia,3.750000,3.500000,4.000000,3.000000,30.500000,25.750000,1.750000,0.750000,1.500000,1.500000,4,4,0.67,10.500000,9.750000,2.750000,3.250000
75,Senegal,Poland,4.333333,4.333333,4.000000,2.666667,31.000000,24.666667,1.333333,1.666667,1.000000,0.666667,3,3,0.67,10.000000,10.000000,1.666667,3.000000
76,Egypt,Russia,5.666667,3.200000,1.666667,3.800000,31.666667,35.200000,2.000000,1.400000,0.666667,2.000000,3,5,0.25,9.666667,9.200000,2.333333,2.200000
77,Morocco,Portugal,6.000000,5.000000,3.333333,3.500000,20.666667,21.750000,1.333333,1.500000,0.666667,1.500000,3,4,0.00,11.666667,13.000000,2.333333,4.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90,Senegal,Japan,4.333333,3.750000,4.000000,4.000000,31.000000,30.500000,1.333333,1.750000,1.000000,1.500000,3,4,0.50,10.000000,10.500000,1.666667,2.750000
91,Columbia,Poland,3.500000,4.333333,3.000000,2.666667,25.750000,24.666667,0.750000,1.666667,1.500000,0.666667,4,3,1.00,9.750000,10.000000,3.250000,3.000000
92,Russia,Uruguay,3.200000,5.200000,3.800000,4.400000,35.200000,21.800000,1.400000,0.600000,2.000000,1.200000,5,5,0.00,9.200000,12.200000,2.200000,2.600000
93,Egypt,Saudi Arabia,5.666667,5.333333,1.666667,3.333333,31.666667,22.333333,2.000000,2.333333,0.666667,0.666667,3,3,0.33,9.666667,12.000000,2.333333,3.333333
94,Morocco,Spain,6.000000,7.000000,3.333333,5.250000,20.666667,9.000000,1.333333,1.500000,0.666667,1.500000,3,4,0.50,11.666667,17.500000,2.333333,5.250000
95,Portugal,Iran,5.000000,5.000000,3.500000,1.333333,21.750000,30.333333,1.500000,0.666667,1.500000,0.333333,4,3,0.50,13.000000,7.000000,4.500000,0.666667
96,Peru,Australia,4.666667,4.666667,3.666667,2.666667,20.000000,27.666667,0.666667,1.666667,0.666667,0.666667,3,3,1.00,10.666667,10.666667,2.333333,3.333333
97,France,Denmark,5.400000,5.500000,3.800000,3.000000,27.000000,26.250000,0.800000,0.500000,1.600000,0.750000,5,4,0.50,11.200000,10.000000,2.000000,1.500000
98,Argentina,Nigeria,4.000000,5.333333,4.500000,3.000000,18.000000,32.000000,2.250000,1.333333,1.500000,1.000000,4,3,0.67,13.250000,13.000000,4.750000,4.666667
99,Croatia,Iceland,7.800000,6.333333,3.800000,4.000000,28.800000,26.666667,0.800000,1.666667,1.800000,0.666667,5,3,0.67,15.600000,12.000000,4.000000,1.666667
100,Germany,Korea Republic,8.000000,3.000000,6.666667,3.666667,11.666667,31.333333,1.333333,1.000000,0.666667,1.000000,3,3,0.00,22.333333,11.000000,7.666667,4.333333
101,Sweden,Mexico,4.400000,6.000000,4.200000,3.250000,37.400000,23.750000,0.800000,1.500000,1.000000,0.750000,5,4,1.00,11.000000,14.250000,2.400000,5.000000
102,Brazil,Serbia,7.000000,5.666667,7.600000,2.333333,18.200000,25.333333,0.600000,1.333333,1.600000,0.666667,5,3,1.00,20.600000,10.666667,6.000000,2.666667
103,Costa Rica,Switzerland,4.333333,5.500000,3.000000,3.500000,32.333333,16.000000,1.666667,1.250000,0.333333,1.250000,3,4,0.50,9.333333,14.000000,2.000000,5.000000
104,Poland,Japan,4.333333,3.750000,2.666667,4.000000,24.666667,30.500000,1.666667,1.750000,0.666667,1.500000,3,4,1.00,10.000000,10.500000,3.000000,2.750000
105,Columbia,Senegal,3.500000,4.333333,3.000000,4.000000,25.750000,31.000000,0.750000,1.333333,1.500000,1.000000,4,3,1.00,9.750000,10.000000,3.250000,1.666667
106,Tunisia,Panama,4.333333,4.333333,4.333333,2.666667,19.333333,24.333333,2.666667,3.666667,1.666667,0.333333,3,3,0.67,12.000000,7.666667,3.333333,0.666667
107,Belgium,England,6.400000,6.000000,6.600000,3.800000,21.000000,15.600000,1.000000,0.800000,2.600000,2.200000,5,5,1.00,17.000000,14.000000,4.000000,4.200000
108,Argentina,France,4.000000,5.400000,4.500000,3.800000,18.000000,27.000000,2.250000,0.800000,1.500000,1.600000,4,5,0.45,13.250000,11.200000,4.750000,2.000000
109,Portugal,Uruguay,5.000000,5.200000,3.500000,4.400000,21.750000,21.800000,1.500000,0.600000,1.500000,1.200000,4,5,0.33,13.000000,12.200000,4.500000,2.600000
110,Russia,Spain,3.200000,7.000000,3.800000,5.250000,35.200000,9.000000,1.400000,1.500000,2.000000,1.500000,5,4,0.50,9.200000,17.500000,2.200000,5.250000
111,Denmark,Croatia,5.500000,7.800000,3.000000,3.800000,26.250000,28.800000,0.500000,0.800000,0.750000,1.800000,4,5,0.50,10.000000,15.600000,1.500000,4.000000
112,Mexico,Spain,6.000000,7.000000,3.250000,5.250000,23.750000,9.000000,1.500000,1.500000,0.750000,1.500000,4,4,0.00,14.250000,17.500000,5.000000,5.250000
113,Japan,Belgium,3.750000,6.400000,4.000000,6.600000,30.500000,21.000000,1.750000,1.000000,1.500000,2.600000,4,5,0.40,10.500000,17.000000,2.750000,4.000000
114,Switzerland,Sweden,5.500000,4.400000,3.500000,4.200000,16.000000,37.400000,1.250000,0.800000,1.250000,1.000000,4,5,0.00,14.000000,11.000000,5.000000,2.400000
115,England,Columbia,6.000000,3.500000,3.800000,3.000000,15.600000,25.750000,0.800000,0.750000,2.200000,1.500000,5,4,0.50,14.000000,9.750000,4.200000,3.250000
116,France,Uruguay,5.400000,5.200000,3.800000,4.400000,27.000000,21.800000,0.800000,0.600000,1.600000,1.200000,5,5,1.00,11.200000,12.200000,2.000000,2.600000
117,Belgium,Brazil,6.400000,7.000000,6.600000,7.600000,21.000000,18.200000,1.000000,0.600000,2.600000,1.600000,5,5,0.67,17.000000,20.600000,4.000000,6.000000
118,England,Sweden,6.000000,4.400000,3.800000,4.200000,15.600000,37.400000,0.800000,0.800000,2.200000,1.000000,5,5,1.00,14.000000,11.000000,4.200000,2.400000
119,Croatia,Russia,7.800000,3.200000,3.800000,3.800000,28.800000,35.200000,0.800000,1.400000,1.800000,2.000000,5,5,0.50,15.600000,9.200000,4.000000,2.200000

In [27]:
#Difference in Opposing Teams
#matches['results']=res
matches['diff_goals_scored']=matches['goals_scored_1']-matches['goals_scored_2']

matches['diff_goals_against']=matches['goals_against_1']-matches['goals_against_2']

matches['diff_attempts_on_target']=matches['attempts_on_target_1']-matches['attempts_on_target_2']

matches['diff_shots_attempted']=matches['shots_attempted_1']-matches['shots_attempted_2']

matches['diff_attempts_off_target']=matches['attempts_off_target_1']-matches['attempts_off_target_2']

matches['diff_shots_blocked']=matches['shots_blocked_1']-matches['shots_blocked_2']

matches['diff_clearances']=matches['clearances_1']-matches['clearances_2']

matches.head()

,Team_1,Team_2,attempts_off_target_1,attempts_off_target_2,attempts_on_target_1,attempts_on_target_2,clearances_1,clearances_2,goals_against_1,goals_against_2,...,shots_attempted_2,shots_blocked_1,shots_blocked_2,diff_goals_scored,diff_goals_against,diff_attempts_on_target,diff_shots_attempted,diff_attempts_off_target,diff_shots_blocked,diff_clearances
0,Russia,Saudi Arabia,3.200000,5.333333,3.800000,3.333333,35.200000,22.333333,1.400000,2.333333,...,12.000000,2.200000,3.333333,1.333333,-0.933333,0.466667,-2.800000,-2.133333,-1.133333,12.866667
1,Egypt,Uruguay,5.666667,5.200000,1.666667,4.400000,31.666667,21.800000,2.000000,0.600000,...,12.200000,2.333333,2.600000,-0.533333,1.400000,-2.733333,-2.533333,0.466667,-0.266667,9.866667
2,Morocco,Iran,6.000000,5.000000,3.333333,1.333333,20.666667,30.333333,1.333333,0.666667,...,7.000000,2.333333,0.666667,0.333333,0.666667,2.000000,4.666667,1.000000,1.666667,-9.666667
3,Portugal,Spain,5.000000,7.000000,3.500000,5.250000,21.750000,9.000000,1.500000,1.500000,...,17.500000,4.500000,5.250000,0.000000,0.000000,-1.750000,-4.500000,-2.000000,-0.750000,12.750000
4,France,Australia,5.400000,4.666667,3.800000,2.666667,27.000000,27.666667,0.800000,1.666667,...,10.666667,2.000000,3.333333,0.933333,-0.866667,1.133333,0.533333,0.733333,-1.333333,-0.666667

In [28]:
#Training Data
columns_of_interest = ['diff_goals_scored','diff_goals_against','diff_attempts_on_target','diff_shots_attempted','diff_attempts_off_target','diff_shots_blocked','diff_clearances']    

train_X = matches[columns_of_interest]

train_Y = matches['results']

from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(n_estimators=100)

train_X[train_X.isnull()]
train_X=train_X.dropna()

rf.fit(train_X,train_Y)
train_Y.head()

0    1.00
1    0.00
2    0.00
3    0.50
4    0.67
Name: results, dtype: float64

In [29]:
#Function to return weight of wining of team_1 against team_2

def winning_probability (team_1,team_2):
    test_matches = pd.DataFrame()
    
    for i in range(len(team_1)):
        first = pd.DataFrame(df[df['Team']==team_1[i]])
        second = pd.DataFrame(df[df['Team']==team_2[i]])
        first = first.reset_index(drop=True)
        second = second.reset_index(drop=True)
        res = pd.DataFrame()

        for col in df.columns:
            res[col+"_1"]=pd.DataFrame(first[col])
            res[col+"_2"]=pd.DataFrame(second[col])
			
        test_matches = test_matches.append(res)
        
        test_matches['goals_scored_1']=test_matches['goals_scored_1']/test_matches['matches_played_1']

        test_matches['goals_scored_2']=test_matches['goals_scored_2']/test_matches['matches_played_2']

        test_matches['goals_against_2']=test_matches['goals_against_2']/test_matches['matches_played_2']

        test_matches['attempts_on_target_2']=test_matches['attempts_on_target_2']/test_matches['matches_played_2']

        test_matches['shots_attempted_2']=test_matches['shots_attempted_2']/test_matches['matches_played_2']

        test_matches['attempts_off_target_2']=test_matches['attempts_off_target_2']/test_matches['matches_played_2']

        test_matches['shots_blocked_2']=test_matches['shots_blocked_2']/test_matches['matches_played_2']

        test_matches['clearances_2']=test_matches['clearances_2']/test_matches['matches_played_2']

        test_matches['goals_against_1']=test_matches['goals_against_1']/test_matches['matches_played_1']

        test_matches['attempts_on_target_1']=test_matches['attempts_on_target_1']/test_matches['matches_played_1']

        test_matches['shots_attempted_1']=test_matches['shots_attempted_1']/test_matches['matches_played_1']

        test_matches['attempts_off_target_1']=test_matches['attempts_off_target_1']/test_matches['matches_played_1']

        test_matches['shots_blocked_1']=test_matches['shots_blocked_1']/test_matches['matches_played_1']

        test_matches['clearances_1']=test_matches['clearances_1']/test_matches['matches_played_1']

        test_matches['diff_goals_scored']=test_matches['goals_scored_1']-test_matches['goals_scored_2']
    
        test_matches['diff_goals_against']=test_matches['goals_against_1']-test_matches['goals_against_2']
    
        test_matches['diff_attempts_on_target']=test_matches['attempts_on_target_1']-test_matches['attempts_on_target_2']
    
        test_matches['diff_shots_attempted']=test_matches['shots_attempted_1']-test_matches['shots_attempted_2']
       
        test_matches['diff_attempts_off_target']=test_matches['attempts_off_target_1']-test_matches['attempts_off_target_2']
    
        test_matches['diff_shots_blocked']=test_matches['shots_blocked_1']-test_matches['shots_blocked_2']
        
        test_matches['diff_clearances']=matches['clearances_1']-matches['clearances_2']
    
        test_X = test_matches[columns_of_interest]
    
        test_X[test_X.isnull()]
    
        test_X=test_X.dropna()
        pred_Y = rf.predict(test_X)
        return pred_Y[0]

#Function to return probability of winning of Team 1 against Team 2

def get_probability (team_1,team_2):
    X1 = winning_probability(team_1,team_2)
    X2 = winning_probability(team_2,team_1)
    X = X1/(X1+X2)
    return X

In [37]:
# Quarter Finals Winning Probabilites: #
print ('Belgium vs France -> %f' %(get_probability(['Belgium'],['France'])))
print ('Croatia vs England -> %f' %(get_probability(['Croatia'],['England'])))

Belgium vs France -> 0.666293
Croatia vs England -> 0.278157